### ISSUE TITLE
timetable get errors

### ISSUE THREAD

**Issue by uwmpr** [RustySnek/librus-apix#17]
Hi i have a problem with getting a timetable here is my code (from example)  
```
from datetime import datetime
from librus_apix.timetable import get_timetable
from librus_apix.get_token import get_token

username = "login"
password = "pass"
token = get_token(username, password)

monday_date = '2023-10-09'
monday_datetime = datetime.strptime(monday_date, '%Y-%m-%d')
timetable = get_timetable(token, monday_datetime)
for weekday in timetable:
  for period in timetable[weekday]:
    print(period.subject, period.teacher_and_classroom)

```

and this is errors

 
```
Traceback (most recent call last):
 
File "/Users/uwmpr/Downloads/librus-apix-main/librus_apix/mojetesty.py", line 15, in <module>
    timetable = get_timetable(token, monday_datetime)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uwmpr/Downloads/librus-apix-main/librus_apix/timetable.py", line 40, in get_timetable
    lesson = periods[period].select(
             ~~~~~~~^^^^^^^^^^^^^
IndexError: list index out of range  
```

 Does anyone want to help me? thanks!  And thanks for this code it helps me a lot with my own project.

**Comment by RustySnek** [comment]
Hey, the issue was with how I counted the periods and it most likely broke down because your school does not have period 0. I've fixed it and it should work now. Feel free to close the issue if you don't encounter any more problems.

**Comment by uwmpr** [comment]
thanks for fix this issue!
